#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Takuma Oda <s21c1027hp@s.chibakoudai.jp>
import sys

ans = 0
for line in sys.stdin:
	try:
		ans += int(line)
	except:
		ans += float(line)

print(ans)
